name: check-all-ci-result
#on:
#  pull_request:
#    branches:
#      - main
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  check-another-ci:
    name: all-check
    runs-on: ubuntu-latest
    steps:
      - uses: lirlia/check-all-ci-completion-action@v1.6.1