name:on_release_publish

on:
  release:
    types: [published]

jobs:
  release:
    name: on_release_publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Set image tag
        shell: bash
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: echo Image Tag
        shell: bash
        run: echo "${IMAGE_TAG}"
